grouptrip/accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name='logout_then_login'),
    url(r'^register/$', views.register, name='register'),
)

grouptrip/grouptrip/urls.py
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('social_auth.urls')),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^trip/', include('trip.urls', namespace="trip")),
    url(r'^invite/', include('invite.urls', namespace="invite")),
    url(r'^finder/', include('finder.urls', namespace="finder")),
    url(r'^tasks/', include('tasks.urls', namespace="tasks")),
    # Examples:
    # url(r'^$', 'socialecom.views.home', name='home'),
    # url(r'^socialecom/', include('socialecom.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

grouptrip/trip/urls.py
from django.conf.urls import patterns, url
from trip import views

urlpatterns = patterns('',
    url(r'^save/$', views.save, name='save'),
    url(r'^profile/(?P<slug>[-\w]+)/$', views.trip_profile, name='profile'),
    url(r'^add_activity/$', views.add_activity, name='add_activity'),
    url(r'^get_activities/$', views.get_activities, name='get_activities'),
    url(r'^get_social_activities/$', views.get_social_activities, name='get_social_activities'),
    url(r'^save_comment/$', views.save_comment, name='save_comment'),
    url(r'^save_review/$', views.save_review, name='save_review'),

)

grouptrip/trip/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Trip(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=255, unique=True,
                            help_text='Unique value for trip page URL, created automatically from name.')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="created_by")
    start_date = models.DateField("Start Date")
    end_date = models.DateField("End Date")
    
    class Meta:
        ordering = ['start_date']
    
    def __unicode__(self):
        return self.name
    
    @models.permalink
    def get_absolute_url(self):
        return ('trip:profile', (), { 'slug': self.slug })


class TripParticipants(models.Model):
    CREATOR = 'creator'
    VIEWER = 'viewer'
    PLANNER = 'planner'
    ROLE_CHOICES = (
        (CREATOR, 'Creator'),
        (VIEWER, 'Viewer'),
        (PLANNER, 'Planner'),
    )
    trip = models.ForeignKey(Trip)
    participant = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="trip_participant")
    role = models.CharField(max_length=100, choices=ROLE_CHOICES, default=VIEWER)

class ActivityItinerary(models.Model):
    RESTAURANT = 'restaurant'
    BAR_CLUB = 'bar_club'
    CONCERT = 'concert'
    ATTRACTION = 'attraction'
    ACTIVITY_CATEGORY_CHOICES = (
        (RESTAURANT, 'Restaurant'),
        (BAR_CLUB, 'Bar/Club'),
        (CONCERT, 'Concert'),
        (ATTRACTION, 'Attraction'),
    )
    
    ACTIVITY_CATEGORY_ICONS = {RESTAURANT:'glyphicon glyphicon-cutlery', 
                               BAR_CLUB:'glyphicon glyphicon-glass', 
                               CONCERT:'glyphicon glyphicon-music', 
                               ATTRACTION:'glyphicon glyphicon-map-marker', '':'glyphicon glyphicon-question-sign'}
    
    trip = models.ForeignKey(Trip)
    name = models.CharField(max_length=500)
    address = models.CharField(max_length=500, blank=True)
    reference = models.CharField(max_length=1000, blank=True)
    start_date = models.DateField("Date", blank=True, null=True)
    start_time = models.TimeField("Time",blank=True, null=True)
    category = models.CharField(max_length=100, choices=ACTIVITY_CATEGORY_CHOICES, blank=True)
    description = models.TextField(blank=True)
    photo = models.URLField(blank=True)
    
    class Meta:
        ordering = ['start_date', 'start_time']

class ActivityComment(models.Model):
    activity = models.ForeignKey(ActivityItinerary)
    comment_by =  models.ForeignKey(settings.AUTH_USER_MODEL)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['created_at']

class ActivityReview(models.Model):
    activity = models.ForeignKey(ActivityItinerary)
    review_by =  models.ForeignKey(settings.AUTH_USER_MODEL)
    rating = models.FloatField()
    description = models.TextField()
    

grouptrip/trip/forms.py
from django import forms
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div, Field
from django.contrib.admin import widgets
from trip.models import Trip, ActivityItinerary

class CreateTripForm(ModelForm):
    class Meta:
        model = Trip
        exclude = ('slug','created_by')
    
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        super(CreateTripForm, self).__init__(*args, **kwargs)
        self.helper.form_class = 'form-horizontal'

class CreateActivityForm(ModelForm):
    class Meta:
        model = ActivityItinerary
        exclude = ('trip')
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        super(CreateActivityForm, self).__init__(*args, **kwargs)
        

grouptrip/trip/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.template.loader import render_to_string
from django.core import serializers
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils import simplejson
from django.utils.text import slugify
from django.template.defaultfilters import date
from trip.forms import CreateTripForm, CreateActivityForm
from trip.models import Trip, TripParticipants, ActivityItinerary, ActivityComment, ActivityReview
from tasks.models import Task
from social_auth.db.django_models import UserSocialAuth
import facebook
import datetime
# Create your views here.


def date_range(start_date, end_date):
    if isinstance(start_date, datetime.datetime):
        start_date = start_date.date()
    if isinstance(end_date, datetime.datetime):
        end_date = end_date.date()
    
    # Verify that the start_date comes after the end_date.
    if start_date > end_date:
        raise ValueError('You provided a start_date that comes after the end_date.')
    
    # Jump forward from the start_date...
    while True:
        yield start_date
        # ... one day at a time ...
        start_date = start_date + datetime.timedelta(days=1)
        # ... until you reach the end date.
        if start_date > end_date:
            break
        
@login_required
def save(request):
    form = CreateTripForm(request.POST)
    if form.is_valid():
        user = request.user
    #trip = Trip(name=request.POST.get('name'), slug=slugify(request.POST.get('name')), created_by=user ,start_date=request.POST.get('start_date'), num_days=request.POST.get('num_days'))
        trip = Trip(name=form.cleaned_data['name'], slug=slugify(form.cleaned_data['name']), created_by=user ,start_date=form.cleaned_data['start_date'], end_date=form.cleaned_data['end_date'])
        trip.save()
        
        trip_participant = TripParticipants(trip=trip, participant=user, role=TripParticipants.CREATOR)
        trip_participant.save()

        template = "trip/trip_summary.html"
        html = render_to_string(template, {'trip_info': trip })
        response = simplejson.dumps({'success':'True', 'html': html})
        
    else:
        html = form.errors.as_ul()
        response = simplejson.dumps({'success':'False', 'html': html})
    return HttpResponse(response, 
                        content_type='application/javascript; charset=utf-8')


@login_required
def add_activity(request):
    activity_id =  request.POST.get('activity_id')
    name = request.POST.get('name')
    address = request.POST.get('address')
    description = request.POST.get('description')
    start_date = request.POST.get('start_date')
    start_time = request.POST.get('start_time')
    category = request.POST.get('category')
    reference = request.POST.get('reference')
    photo = request.POST.get('photo')
    slug = request.POST.get('slug')

    #TODO verify user is either creator or planner
    
    form = CreateActivityForm({'name':name, 'address':address, 'reference':reference, 'start_date':start_date,'start_time':start_time, 'category':category, 'description':description, 'photo':photo})
    #TODO: check if form submitted is valid, if not, pass back error to javascript function
    
    if form.is_valid():
        if activity_id:
            activity = get_object_or_404(ActivityItinerary, pk=activity_id)
            activity.name = form.cleaned_data['name']
            activity.address = form.cleaned_data['address']
            activity.description = form.cleaned_data['description']
            activity.start_date = form.cleaned_data['start_date']
            activity.start_time = form.cleaned_data['start_time']
            activity.category = form.cleaned_data['category']
            activity.photo = form.cleaned_data['photo']
            edited = 'True'
        else:
            trip = get_object_or_404(Trip, slug=slug)
            activity = ActivityItinerary(name=form.cleaned_data['name'], trip=trip, reference=form.cleaned_data['reference'], start_date=form.cleaned_data['start_date'], 
                                         start_time=form.cleaned_data['start_time'], address=form.cleaned_data['address'], 
                                         category=form.cleaned_data['category'], description=form.cleaned_data['description'], photo=form.cleaned_data['photo'])
            edited = 'False'
            
        activity.save()
        template = "trip/activity_summary2.html"
        #TODO:is there a better way to figure out which div this activity panel goes into?
        formatted_date = date(activity.start_date, "Y-m-d")
        activities_div_id = "#my%sActivities" % formatted_date
        no_activities_div_id = "#no%sActivities" % formatted_date
        html = render_to_string(template, {'activity': activity})
        response = simplejson.dumps({'success':'True', 'html': html, 'activities_div_id':activities_div_id, 'no_activities_div_id':no_activities_div_id, 'edited':edited})
    
    else:
        print(form.errors.as_ul())
        html = form.errors.as_ul()
        response = simplejson.dumps({'success':'False', 'html': html})
    return HttpResponse(response, 
                        content_type='application/javascript; charset=utf-8')


@login_required
def get_activities(request):
    slug = request.GET.get('slug')
    #TODO make sure user is in this trip
    trip = get_object_or_404(Trip, slug=slug)
    activities = trip.activityitinerary_set.all()
    #TODO consider using serializers everywhere instead of simplejson
    response = serializers.serialize("json", activities, fields=('name', 'reference', 'address'))
    
    return HttpResponse(response, 
                        content_type='application/javascript; charset=utf-8')

@login_required
def get_social_activities(request):
    slug = request.GET.get('slug')
    trip = get_object_or_404(Trip, slug=slug)
    #TODO get only activities that your friends were participants in
    trip_activities = trip.activityitinerary_set.values_list('pk', flat=True)
    #TODO:exclude activities that belong to trips that this user was in
    #trips_participated = request.user.trip_participant.values_list('trip', flat=True)
    social_activities = ActivityItinerary.objects.exclude(pk__in=list(trip_activities))
    template = "trip/review_summary.html"
    activities_reviews_info= []
    for social_activity in social_activities:
        activity_reviews = social_activity.activityreview_set.all()
        activity_reviews_info = {}
        activity_reviews_info['name'] = social_activity.name
        activity_reviews_info['address'] = social_activity.address
        activity_reviews_info['reviews'] = []
        for activity_review in activity_reviews:
            instance = UserSocialAuth.objects.filter(provider='facebook').get(user=activity_review.review_by)
            graph = facebook.GraphAPI(instance.tokens['access_token'])
            user_profile = graph.get_object("me", fields="id, name, first_name, last_name, picture")
            html = render_to_string(template, {'activity_review': activity_review, 'reviewer_profile':user_profile})
            activity_reviews_info['reviews'].append(html)
        activities_reviews_info.append(activity_reviews_info)
    
    response = simplejson.dumps({'success':'True', 'activities_reviews_info':activities_reviews_info})      
    return HttpResponse(response, 
                        content_type='application/javascript; charset=utf-8')

@login_required
def save_comment(request):
    activity_id = request.POST.get('activity_id')
    comment = request.POST.get('comment')
    comment_by = request.user
    activity = get_object_or_404(ActivityItinerary, pk=activity_id)
    activity_comment = ActivityComment(activity=activity, comment_by=comment_by, comment=comment)
    activity_comment.save()
    
    template = "trip/comment.html"
    instance = UserSocialAuth.objects.filter(provider='facebook').get(user=request.user)
    graph = facebook.GraphAPI(instance.tokens['access_token'])
    user_profile = graph.get_object("me", fields="id, name, first_name, last_name, picture")
    
    html = render_to_string(template, {'activity_comment': activity_comment, 'commentor_profile':user_profile})
    response = simplejson.dumps({'success':'True', 'html':html})
    return HttpResponse(response, 
                        content_type='application/javascript; charset=utf-8')
    
@login_required
def save_review(request):
    activity_id = request.POST.get('activity_id')
    rating = request.POST.get('rating')
    description = request.POST.get('description')
    review_by = request.user
    activity = get_object_or_404(ActivityItinerary, pk=activity_id)
    activity_review = ActivityReview(activity=activity, rating=rating, description=description, review_by=review_by)
    activity_review.save()
    
    template = "trip/review_summary.html"
    instance = UserSocialAuth.objects.filter(provider='facebook').get(user=request.user)
    graph = facebook.GraphAPI(instance.tokens['access_token'])
    user_profile = graph.get_object("me", fields="id, name, first_name, last_name, picture")
    
    html = render_to_string(template, {'activity_review': activity_review, 'reviewer_profile':user_profile})
    response = simplejson.dumps({'success':'True', 'html':html})
    return HttpResponse(response, 
                        content_type='application/javascript; charset=utf-8')

def trip_profile(request, slug):
    #TODO:either the trip is created by the user, or user is part of it
    trip = get_object_or_404(Trip, slug=slug)
    #TODO:get only the user objects instead of the TripParticipants objects
    trip_participants = trip.tripparticipants_set.all()

grouptrip/trip/templates/trip/activities.html
{% load trip_extras %}
<div id="activity_content" class="activity-carousel carousel slide">
	<div class="carousel-inner">
		<div class="item active">
			{% for date in dates %}
				<div class="alert alert-success">
					<strong>Day {{ forloop.counter}}: {{ date }}</strong>
					<div class="pull-right">
						<a data-toggle="collapse" href="#my{{date|date:"Y-m-d"}}Activities"><small>Show   <span class="glyphicon glyphicon-chevron-down"></span></small></a>
					</div>
				</div>
				<div id="my{{ date|date:"Y-m-d" }}Activities" class="collapse in">
					{% if date in activities %}
						{% for activity in activities|lookup:date %}
							{% include "trip/activity_summary2.html" with user=user user_profile=user_profile user_participants_social_pf=user_participants_social_pf activity=activity activity_category_icon=activity_category_icons|lookup:activity.category%}
						{% empty %}
							<div id="no{{ date|date:"Y-m-d" }}Activities" class="text-center">
								<strong>No Activities for this day</strong>
							</div>
							<br>
						{% endfor %}
					{% endif %}
				</div>
			{% endfor %}
	    </div>
	</div>
</div>



	

grouptrip/trip/templates/trip/activity_summary2.html
{% load staticfiles %}
<div id="{{activity.id}}_activity_summary">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">
				<div class="row">
					<div class="col-lg-8">
				  		<span class="{{activity_category_icon}} icons"></span>{{activity.name}}
				  	</div>
				  	<div class="col-lg-4">
				  		<div class="pull-right">
					  		<a href="#" class="edit-activity" data-activity-id="{{activity.id}}" data-activity-name="{{activity.name}}" data-activity-start-date="{{activity.start_date|date:"m/d/Y"}}"
					  		data-activity-start-time="{{activity.start_time|time:"H:i"}}" data-activity-address="{{activity.address}}" data-activity-description="{{activity.description}}" data-activity-category="{{activity.category}}">
					  			<span class="glyphicon glyphicon-edit"></span> 
					  		</a>
					  		<a href="#" class="review-link" data-activity-id="{{activity.id}}">
					  			<span class="glyphicon glyphicon-star"></span> 
					  		</a>
					  		<a href="#" class="discussion-link" data-activity-id="{{activity.id}}">
					  			<span class="glyphicon glyphicon-comment"></span> 
					  		</a>
				  		</div>
				  	</div>
				  </div>
			</h3>
		</div>
		<div class="panel-body">
			<div class="container">
				<div id="{{activity.id}}_activity_summary_content" class="activity-summary-content carousel slide">
					<div class="carousel-inner">
					    <div class="item active">
					    	<div class="media">
								  <a class="pull-left" href="#">
								    <img id="{{ activity.id }}activityPicture" class="media-object" src="{{ activity.photo }}">
								  </a>
								<div class="media-body">
								    <h5>{{ activity.address }}</h5>
								    <p><span class="glyphicon glyphicon-time"></span> {{ activity.start_time }}</p>
							    	<a data-toggle="collapse" href="#{{ activity.id }}activityContent"><small>Show More <span class="glyphicon glyphicon-chevron-down"></span></small></a>
								    <div class="pull-right">				
								    	<button type="button" class="btn btn-info btn-xs show-on-map" data-name="{{activity.name}}">Show on Map</button>
									</div>
								</div>
							</div>
							<div class="collapse" id="{{ activity.id }}activityContent">
							  	<hr>
							  	<strong>Description:</strong> 
							  	{% if activity.description %}
								    {{ activity.description }}
								{% else %}
								    No Description.
								{% endif %}
							</div>
						</div>
						<div class="item">
							{% include "trip/reviews.html" with user=user user_profile=user_profile user_participants_social_pf=user_participants_social_pf activity_id=activity.id activity_reviews=activity.activityreview_set.all%}
						</div>
						<div class="item">
							{% include "trip/discussion.html" with user=user user_profile=user_profile user_participants_social_pf=user_participants_social_pf activity_id=activity.id activity_comments=activity.activitycomment_set.all%}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

grouptrip/trip/templates/trip/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load trip_extras %}
	<head>
	    <title>{% block title %}My amazing site{% endblock %}</title>
	    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
	    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
	    <link href="{% static "trip/trip.css" %}" rel="stylesheet" media="screen">
	</head>

	
	<body>
	        {% block navbar %}
	        	<div class="navbar navbar-inverse navbar-fixed-top">
    					<a class="navbar-brand" href="#">GroupTrip</a>
    					<ul class="nav navbar-nav">
     						 <li class="active"><a href="{% url 'accounts:profile'%}">Home</a></li>
    					</ul>
    					<ul class="nav navbar-nav navbar-right">
    						 <li class="dropdown">
    						 	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									{{user_profile.name}} <b class="caret"></b>
    						 	</a>
    						 	<ul class="dropdown-menu">
						          <li><a href="{% url 'accounts:logout_then_login'%}">Logout</a></li>
						        </ul>
    						 </li>
    					</ul>
				</div>
	        {% endblock %}
	        
	        {% block content %}
	        {% endblock %}
	        <script src="http://code.jquery.com/jquery.js"></script>
	       	<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
			<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
			<script type="text/javascript" src="{% static "jquery.raty.min.js" %}"></script>
			<script type="text/javascript" src="http://twitter.github.io/typeahead.js/releases/latest/typeahead.min.js"></script>
			<script type="text/javascript" src="{% static "trip/scripts.js" %}"></script>
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBABrAliBhsGpLAQ6vZ675rShv7yyr_k2U&sensor=false&libraries=places"></script>
			<script type="text/javascript" src="{% static "invite/scripts.js" %}"></script>			
	</body>
</html>

grouptrip/trip/templates/trip/create_activity.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<div id="createActivity" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Create Activity</h4>
      </div>
      <div class="modal-body">
        <form id="createActivityForm" class="form-horizontal">
		  <div class="form-group">
		  	<div class="col-lg-3">
		    	<label for="id_name" class="control-label pull-right">Name</label>
		    </div>
		    <div class="col-lg-8">
		      <input type="text" class="form-control pull-left" id="id_name" maxlength="500" name="name" placeholder="Enter Name">
		    </div>
		  </div>
		  <div class="form-group row">
		  	<div class="col-lg-3">
		    	<label for="id_start_date" class="control-label pull-right">Date</label>
		    </div>
		    <div class="col-lg-3">
		      <input type="text" class="form-control pull-left" id="id_start_date" name="start_date" placeholder="Date">
		    </div>
		    <div class="col-lg-2">
		    	<label for="id_start_time" class="control-label pull-right">Time</label>
		    </div>
		    <div class="col-lg-3">
		      <input type="text" class="form-control pull-left" id="id_start_time" name="start_time" placeholder="Time">
		    </div>
		  </div>
		  <div class="form-group">
		  	<div class="col-lg-3">
		    	<label for="id_category" class="control-label pull-right">Category</label>
		    </div>
		    <div class="col-lg-5">
		      <select id="id_category" name="category" class="form-control pull-left input-sm">
				<option value="" selected="selected">---------</option>
				<option value="restaurant">Restaurant</option>
				<option value="attraction">Attraction</option>
			  </select>
		    </div>
		  </div>
		  <div class="form-group">
		  	<div class="col-lg-3">
		    	<label for="id_address" class="control-label pull-right">Address</label>
		    </div>
		    <div class="col-lg-8">
		      <input type="text" class="form-control pull-left" id="id_address" maxlength="500" name="address" placeholder="Enter Address">
		    </div>
		  </div>
		  
		  
		  <div class="collapse" id="activity_photo_collapse">
				<div class="form-group">
				  	<div class="col-lg-3">
				    	<label for="id_activity_photo" class="control-label pull-right">Choose a Photo</label>
				    </div>
				    <div class="col-lg-8" id="id_activity_photo">
				    </div>
				</div>
		  </div>
		  
		  
		  <div class="form-group">
		  	<div class="col-lg-3">
		    	<label for="id_description" class="control-label pull-right">Description</label>
		    </div>
		    <div class="col-lg-8">
		      <textarea class="form-control pull-left" id="id_description" name="description" rows="3" placeholder="Enter Description"></textarea>
		    </div>
		    <input type="hidden" id="id_activity_id" />
		    <input type="hidden" id="id_reference" />
		  </div>
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="onSaveActivity()">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

grouptrip/trip/templates/trip/trip_profile.html
{% extends "trip/base.html" %}
{% load staticfiles %}
{% block title %}Welcome Home!{% endblock %}
{% load trip_extras %}

{% block content %}


	{% include "trip/create_activity.html"%}
	<input type="hidden" id="id_slug" value="{{ trip.slug }}" />
<script language="javascript">var STATIC_URL = "{{ STATIC_URL }}";</script>
<div class="container">	
	<div class="jumbotron">
	      <div class="container">
	        <h2>{{trip.name}}</h2>
	        <p>{{trip.start_date}}-{{trip.end_date}}</p>
	        <p>
	        	<small>Participants:</small>
	        	<img src="{{user_profile.picture.data.url}}">
	        	{% for user_participant in user_participants_social_pf %}
	        		{% with user_participant_social_pf=user_participants_social_pf|lookup:user_participant %}     
	        			<img src="{{user_participant_social_pf.picture.data.url}}">
	        		{% endwith %}
	        	{% endfor %}
	        </p>
	      </div>
	</div>

	
	<div class="row">
		<div class="col-lg-12">
			<div class="btn-group btn-group-justified btn-nav-group" data-toggle="buttons">
			  <label class="btn btn-success nav-options"  data-target="#itinerary">
			    <input type="radio"><strong><span class="glyphicon glyphicon-calendar"></span>  Itinerary</strong>
			  </label>
			  <label class="btn btn-success nav-options"  data-target="#finder">
			    <input type="radio"><strong><span class="glyphicon glyphicon-search"></span>  Finder</strong>
			  </label>
			  <label class="btn btn-success nav-options" data-target="#tasks">
			    <input type="radio"><strong><span class="glyphicon glyphicon-tasks"></span>  Tasks</strong>
			  </label>
			  <label class="btn btn-success nav-options" data-target="#">
			    <input type="radio"><strong><span class="glyphicon glyphicon-pencil"></span>  Surveys</strong>
			  </label>
			  <label class="btn btn-success nav-options" data-target="#">
			    <input type="radio"><strong><span class="glyphicon glyphicon-usd"></span>  Costs</strong>
			  </label>
			  <label class="btn btn-success nav-options" data-target="#">
			    <input type="radio"><strong><span class="glyphicon glyphicon-picture"></span>  Photo Album</strong>
			  </label>
			  <label class="btn btn-success nav-options" data-target="#invite">
			    <input type="radio"><strong><span class="glyphicon glyphicon-user"></span>  Invite</strong>
			  </label>
			</div>
		</div>
		
		<div class="container">
			<div class="tab-content">
			  	<!--Content of Itinerary Tab-->
			  	<div class="tab-pane active" id="itinerary">
			  			{% include "trip/itinerary2.html" with user=user user_profile=user_profile user_participants_social_pf=user_participants_social_pf activities=activities dates=dates activity_category_icons=activity_category_icons%}
			  	</div>
			  	<!--Content of Finder Tab-->
			  	<div class="tab-pane" id="finder">
			  			{% include "finder/finder.html"%}
			  	</div>
			  	<!--Content of Tasks Tab-->
			  	<div class="tab-pane" id="tasks">
			  			{% include "tasks/tasks.html" with tasks=tasks trip_participants=trip_participants%}
			  	</div>
			  	<!--Content of Invite Tab-->
			  	<div class="tab-pane" id="invite">
			  			{% include "invite/invite.html" with user_list=user_list trip_participants=trip_participants%}
			  	</div>
			</div>
			<div class="col-lg-6">
			  		{% include "googlemaps/map.html" %}
			</div>
		</div>
	</div>
</div>


{% endblock %}
 
 
 
 
 

grouptrip/trip/templates/trip/trip_summary.html
<tr>
	<td>
		<a href="{{trip_info.get_absolute_url}}">
			{{ trip_info.name }}
		</a>
		</td>
		<td>{{ trip_info.start_date }}</td>
		<td>{{ trip_info.end_date }}</td>
</tr>